### ISSUE TITLE
TabBar not align with safe area for new iPhone models

### ISSUE THREAD

**Issue by geogerar** [yunuserenguzel/sliding-tabbar-controller#1]
Hi,
I use your SlidingTabBarController many many times and I can say It is a fantastic Tool.
But with the new models of iPhone ( X, XR, etc) the TabBar is not align with constraints according to safe area.
TabBar goes on safe area.
Is it possible to correct this issue or to give me some hints how to correct this by myself?

I thank you in advance.

George Gerardis

**Comment by yunuserenguzel** [comment]
Hello George,

Thanks for the kind words. I updated the pod with iPhone X variants support. Let me know if it works. I am also planning to migrate to Swift 5 as well as refactoring the code a little bit. 

Best, 
Yunus
